### ISSUE TITLE
Dein Code in Version 2.0

### ISSUE THREAD

**Issue by all-solutions** [ISharkI/SuperrolloGW60Automation#1]
Ich habe Deinen Quellcode rein zufällig gefunden. Da ich meine Projekte bei GitLab hoste, ist das schwierig, die zwei zu vereinen...
Hoffe, Du bist mir nicht böse. Ich habe da in den letzten Wochen Einiges umgeschrieben und erweitert. Link als Bezug hierhin steht als Comment in der ersten Zeile ;-)
https://gitlab.com/ManuA/GW60-Superrollo

**Comment by ISharkI** [comment]
Hi,
schön das es dich interessiert, über einen eventuellen Merge-Request hier würde ich mich natürlich freuen.

Was mir aber gerade aufgefallen ist: Mein Code hier ist unter GPL lizensiert, dann kannst du nicht plötzlich unter Apache lizensieren. Zumindest die Teile die auf meinem Code basieren müssen ebenfalls unter GPL lizensiert sein.

**Comment by all-solutions** [comment]
Merge wird schwer werden über die Plattformen. Zumal da zig Sachen geändert wurden von mir. Hast Dir den Code mal angesehen? Der ist kaum mit Deinem mehr zu vergleichen. 
Für den Lizenz-Wechsel entschuldige ich mich natürlich. Apache ist gelöscht und wird selbstverständlich durch GPL ersetzt. 

P.S.: Nur so ganz nebenbei: hätte ich mich eben eigentlich nicht für bedanken wollen, dass Du mir diesen Denkanstoß gegeben hast, hättest Du nie erfahren, dass ich überhaupt mal auf dieser Seite hier war. Schau Dir meinen Code mal in Ruhe an. Da sind keine 10% -wenn überhaupt- von Deinem Code drin...

**Comment by ISharkI** [comment]
10% sind lizenzrechtlich immernoch 10%, ob ich davon jetzt oder später was mitbekomme oder nicht ist nebensächlich.

Ich hab da jetzt auch nicht vor irgendwas gegen zu tun, sollte nur ein weitere Denkanstoß sein

Zum Merge-Request: du kannst mir auch ein git patch von jetzt zu dem commit mit der ersten version schicken, dann kann man das sicher auch einbauen.

**Comment by all-solutions** [comment]
OK, reicht!
Ich habe es auf GPL umgestellt, Lizenz erfüllt!

Ich werde aber die vorhandenen 10% aus dem Code entfernen bzw. ersetzen. Inklusive dem Credit-Comment in der ersten Zeile. 
Wieso bin ich nur auf die blöde Idee gekommen, mich für einen Denkanstoß bedanken zu wollen...
Du kannst Dir Morgen den Code ansehen. Wenn da noch was ist, was Du beanspruchen möchtest, sag Bescheid.  
Dann hat sich auch das Thema Merge erledigt...

**Comment by ISharkI** [comment]
Also ich weiß nicht wo da jetzt das Problem ist? DAs war wirklich als konstruktiver Hinweis gedacht, weil ich das aus Projekten kennen wo es später (teilweise Jahre später) probleme gemacht hat und der Code nicht weiter verwendet werden konnte.

Wenn dich das soweit stört, dass du deine Agressivität an Leuten auslassen musst, solltest du den  OpenSource Ansatz nochmal überdenken.
